### PR TITLE
V3.0

### PR DESCRIPTION
**Pull request by ShixiangWang**
@tlesluyes Hi, here are my changes when using this version on WES. If the PR is not acceptable, please note a bug introduced by gender assertion in your latest commit (https://github.com/tlesluyes/ascat/blob/9f2b8796b668e53b76e4aeb39ef5bf5680fe15dc/ASCAT/R/ascat.prepareHTS.R#L54) should be fixed by hand.

image

Best,

Shixiang

### CODE REVIEW

**Comment by tlesluyes** [comment]
Hi Shixiang,

I'm not seeing any bug relative to *gender* in the latest version, perhaps it was fixed in a previous commit. As mentioned, this still is a version under development so it will be subjected to major changes in the near future. Therefore, I will not accept any external PR now.

Cheers,

Tom.

**Comment by ShixiangWang** [comment]
Hi Tom,

please double-check the code, as I used the v3.0 code recently for my data. I can see the bug still exists in the latest commit of v3.0.

You can check the following parts or test the latest commit code by calling `ascat.prepareHTS()` with example data:
 https://github.com/tlesluyes/ascat/blob/3a3df5254bea9f442491726cc8c266b4ada66316/ASCAT/R/ascat.prepareHTS.R#L219-L222

> no `gender` here

https://github.com/tlesluyes/ascat/blob/3a3df5254bea9f442491726cc8c266b4ada66316/ASCAT/R/ascat.prepareHTS.R#L258-L269


> no `gender` here

As for the PR, it is okay for me to maintain a fork version.

Best,

Shixiang

**Comment by tlesluyes** [comment]
You're right, I wasn't using *ascat.prepareHTS*, just its sub-functions so I haven't been through the issue until now. Should be fixed now, thanks for spotting this!

**Comment by ShixiangWang** [comment]
you're welcome.

**Pull request closed without merging**
